version: 2
registries:
  maven-repository-build-tis-nhs-uk-maven-repository:
    type: maven-repository
    url: https://build.tis.nhs.uk/maven/repository
    username: gradle
    password: "${{secrets.MAVEN_REPOSITORY_BUILD_TIS_NHS_UK_MAVEN_REPOSITORY_PASSWORD}}"

updates:
- package-ecosystem: gradle
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: com.amazonaws:aws-java-sdk-s3
    versions:
    - 1.11.1001
    - 1.11.1002
    - 1.11.1003
    - 1.11.1005
    - 1.11.945
    - 1.11.946
    - 1.11.947
    - 1.11.948
    - 1.11.949
    - 1.11.950
    - 1.11.951
    - 1.11.952
    - 1.11.953
    - 1.11.954
    - 1.11.955
    - 1.11.956
    - 1.11.957
    - 1.11.958
    - 1.11.959
    - 1.11.960
    - 1.11.961
    - 1.11.962
    - 1.11.963
    - 1.11.964
    - 1.11.965
    - 1.11.966
    - 1.11.968
    - 1.11.969
    - 1.11.971
    - 1.11.972
    - 1.11.973
    - 1.11.974
    - 1.11.975
    - 1.11.976
    - 1.11.977
    - 1.11.978
    - 1.11.979
    - 1.11.980
    - 1.11.981
    - 1.11.983
    - 1.11.986
    - 1.11.987
    - 1.11.988
    - 1.11.990
    - 1.11.991
    - 1.11.992
    - 1.11.993
    - 1.11.994
    - 1.11.996
    - 1.11.997
    - 1.11.998
  - dependency-name: io.sentry:sentry-spring
    versions:
    - 4.0.0
    - 4.1.0
    - 4.2.0
    - 4.3.0
  - dependency-name: org.springframework.boot
    versions:
    - 2.4.2
  - dependency-name: org.mapstruct:mapstruct-processor
    versions:
    - 1.4.1.Final
  - dependency-name: org.mapstruct:mapstruct
    versions:
    - 1.4.1.Final
  registries:
  - maven-repository-build-tis-nhs-uk-maven-repository
