application:
  signature:
    secret-key: test-secret-key
  aws:
    sns:
      formr-file-event: dummy
      formr-refresh: dummy-formr-refresh
      formr-updated: dummy
      ltft-refresh: dummy-ltft-refresh
    sqs:
      coj-received: dummy
      notification-event: dummy
      profile-move: dummy
  schedules:
    publish-all-formr-partas: "-"
    publish-all-formr-partbs: "-"
    publish-all-ltfts: "-"

mongock:
  enabled: false

spring:
  cloud:
    aws:
      region:
        static: eu-west-2
      sqs:
        enabled: false
