name: PR Analysis

on:
  pull_request:
    branches:
      - main

jobs:
  analysis:
    name: Analyse PR
    uses: health-education-england/.github/.github/workflows/pr-analysis-gradle.yml@main
    with:
      java-version: 17.0.14+7
    secrets:
      sonar-token: ${{ secrets.SONAR_TOKEN }}
