name: PR Analysis

on:
  pull_request:
    branches:
      - validationfailure-worflowchange

jobs:
  analyse:
    name: Analyse PR
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4.0.0
        with:
          distribution: temurin
          java-version: 17.0.14

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Build
        run: ./gradlew build
