name: PR Analysis

on:
  pull_request:
    branches:
      - main

jobs:
  analyse:
    name: Analyse PR
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK
        uses: actions/setup-java@v4.0.0
        with:
          cache: gradle
          distribution: temurin
          java-version: 17.0.14+7

      - name: Build
        run: ./gradlew build
